# Generated by Django 5.2.7 on 2025-11-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='message',
            new_name='Message',
        ),
    ]
