# Generated by Django 5.2.7 on 2025-11-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_rename_message_contactdb_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDB',
        ),
    ]
